
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udr
  template:
    metadata:
      labels:
        app: udr
    spec:
      initContainers:
      - name: wait-udm
        image: busybox:1.32.0
        env:
        - name: DEPENDENCIES
          value: udm-nudm:8000
        command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the SMF; sleep 2; done;"]
      containers:
      - name: udr
        image: free5gc/udr:v3.4.1
        imagePullPolicy: Always
        command: ["./udr", "-c", "./config/udrcfg.yaml"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: udr-volume
          mountPath: /free5gc/config/
        env:
        - name: DB_URI
          value: "mongodb://db/free5gc"
        - name: GIN_MODE
          value: "release"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: udr-volume
        projected:
          sources:
          - configMap:
              name: udr-configmap
