apiVersion: apps/v1
kind: Deployment
metadata:
  name: ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ausf
  template:
    metadata:
      labels:
        app: ausf
    spec:
      initContainers:
      - name: wait-amf
        image: busybox:1.32.0
        env:
        - name: DEPENDENCIES
          value: amf-namf:8000
        command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the AMF; sleep 2; done;"]
      containers:
      - name: ausf
        image: free5gc/ausf:v3.4.1
        imagePullPolicy: IfNotPresent
        command: ["./ausf", "-c", "./config/ausfcfg.yaml"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: ausf-volume
          mountPath: /free5gc/config/
        env:
        - name: GIN_MODE
          value: "release"
      volumes:
      - name: ausf-volume
        projected:
          sources:
          - configMap:
              name: ausf-configmap
              