apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
      # annotations:
      #   k8s.v1.cni.cncf.io/networks: '[
      #     { "name": "5gnetwork", "interface": "eth1", "ips": [ "129.97.168.120/24" ] }
      #     ]'
    spec:
      containers:
      - name: webui
        image: free5gc/webui:v3.4.1
        command: ["./webui", "-c", "./config/webuicfg.yaml"]
        ports:
        - containerPort: 5000
        - containerPort: 2122
        - containerPort: 2121
        volumeMounts:
        - name: webui-volume
          mountPath: /free5gc/config/
        env:
        - name: GIN_MODE
          value: "release"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: webui-volume
        projected:
          sources:
          - configMap:
              name: webui-configmap