apiVersion: v1
kind: ConfigMap
metadata:
  name: n3iwf-configmap
data:
  n3iwfcfg.yaml: |-
    info:
      version: 1.0.5
      description: N3IWF initial local configuration

    configuration:
      N3IWFInformation:
        GlobalN3IWFID: # ID used to globally identify an N3IWF
          PLMNID: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
            MCC: 208 # Mobile Country Code (3 digits string, digit: 0~9)
            MNC: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
          N3IWFID: 135 # ID used to identify an N3IWF in PLMN (uinteger, range: 0~65535)
        Name: free5GC_N3IWF # The name of this N3IWF
        SupportedTAList: # Tracking Area supported by this N3IWF
          - TAC: 000001 # Tracking Area Code (3 bytes hex string, range: 000000~FFFFFF)
            BroadcastPLMNList: # Refer to TS 38.413
              - PLMNID: # Public Land Mobile Network ID
                  MCC: 208 # Mobile Country Code (3 digits string, digit: 0~9)
                  MNC: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
                TAISliceSupportList: # Network Slice supported in this TAI
                  - SNSSAI: # Single Network Slice Selection Assistance Information
                      SST: 1 # Slice/Service Type (1 byte hex string, range: 0~F)
                      SD: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
                  - SNSSAI: # Single Network Slice Selection Assistance Information
                      SST: 1 # Slice/Service Type (1 byte hex string, range: 0~F)
                      SD: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)

      # --- N2 Interfaces ---
      AMFSCTPAddresses: # the IP list of N2 interfaces (SCTP) on AMF when using NGAP
        - IP:
          - 129.97.168.161 # amf.free5gc.org
          Port: 38412
      NASTCPPort: 20000 # TCP port which the NAS listens on

      # --- Nwu Interfaces ---
      IKEBindAddress: 129.97.168.140 # Nwu interface  IP address (IKE) on this N3IWF
      IPSecTunnelAddress: 129.97.168.140 # 10.100.200.15 # Tunnel IP address of XFRM interface on this N3IWF
      UEIPAddressRange: 129.97.168.0/24 # 10.100.200.0/24 # IP address pool allocated to UE in IPSec tunnel
      XFRMInterfaceName: xfrmi # Prefix of XFRM interface name created by N3IWF
      XFRMInterfaceID: 1 # XFRM interface if_id for IPSec routing (Any value except to 0, default value is 7 if not defined)

      # --- N3 Interfaces ---
      GTPBindAddress: 129.97.168.140 # 10.100.200.15 # IP address of N3 interface (GTP) on this N3IWF

      FQDN: 129.97.168.140 # n3iwf.free5gc.org # FQDN of this N3IWF

      # --- Security ---
      PrivateKey: cert/n3iwf.key # Private key file path
      CertificateAuthority: cert/n3iwf.pem # Certificate Authority (CA) file path
      Certificate: cert/n3iwf.pem # Certificate file path

      # sending dead peer detection message
      LivenessCheck:
        enable: true # true or false
        transFreq: 60s # frequency of transmission
        maxRetryTimes: 4 # the max number of DPD response of UE

    logger: # log output setting
      enable: true # true or false
      level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      reportCaller: false # enable the caller report or not, value: true or false

  n3iwf-ipsec.sh: |-
    #!/bin/sh

    ### N3iwf IPSec tunnel configuration

    # As per https://github.com/free5gc/free5gc/issues/45#issuecomment-634012712
    #     IKEBindAddress: dynamically computed by $(hostname -i | awk '{print $1}')
    #     IPSecInterfaceMark: 5
    #     IPSecInterfaceAddress: 10.0.0.1
    #     IPSec subnet CIDR: /24
    #     N3IWF tunnel interface: ipsec0
    #     

    ip link add name ipsec0 type vti local $(hostname -i | awk '{print $1}') remote 0.0.0.0 key 5
    ip addr add 129.97.168.140/24 dev ipsec0
    ip link set dev ipsec0 up