apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: 
  labels:
    app.kubernetes.io/name: mongodb
spec:
  type: NodePort
  ports:
    - name: mongodb
      port: 27017
      nodePort: 30000
  selector:
    app.kubernetes.io/name: mongodb