apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      labels:
        app: smf
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n4network", "interface": "n4", "ips": [ "10.10.4.101/24" ] }
          ]'
    spec:
      initContainers:
      - name: wait-ausf
        image: busybox:1.32.0
        env:
        - name: DEPENDENCIES
          value: ausf-nausf:8000
        command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the AUSF; sleep 2; done;"]
      containers:
      - name: smf
        image: free5gc/smf:v3.4.1
        imagePullPolicy: Always
        command: ["./smf", "-c", "./config/smfcfg.yaml", "-u", "./config/uerouting.yaml"]
        ports:
        - name: nsmf
          containerPort: 8000
        - name: pfcp
          containerPort: 8805
          protocol: UDP
        volumeMounts:
        - name: smf-volume
          mountPath: /free5gc/config/
        env:
        - name: GIN_MODE
          value: "release"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: smf-volume
        configMap:
          name: smf-configmap
          items:
          - key: smfcfg.yaml
            path: smfcfg.yaml
          - key: uerouting.yaml
            path: uerouting.yaml
