apiVersion: v1
kind: Service
metadata:
  name: webui-service
spec:
  type: NodePort
  selector:
    app: webui
  ports:
    - name: http
      port: 5000
      nodePort: 30530
    # - name: http1
    #   port: 2121
    #   nodePort: 30531
    # - name: http2
    #   port: 2122
    #   nodePort: 30532