apiVersion: apps/v1
kind: Deployment
metadata:
  name: nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nssf
  template:
    metadata:
      labels:
        app: nssf
    spec:
      initContainers:
        - name: wait-udr
          image: busybox:1.32.0
          env:
          - name: DEPENDENCIES
            value: udr-nudr:8000
          command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the UDR; sleep 2; done;"]
      containers:
      - name: nssf
        image: free5gc/nssf:v3.4.1
        imagePullPolicy: IfNotPresent
        command: ["./nssf", "-c", "./config/nssfcfg.yaml"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: nssf-volume
          mountPath: /free5gc/config/
        env:
        - name: GIN_MODE
          value: "release"
      volumes:
      - name: nssf-volume
        projected:
          sources:
          - configMap:
              name: nssf-configmap